services:
  - type: web
    name: leetbattle-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: FRONTEND_ORIGIN
        sync: false
      - key: JUDGE0_URL
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
